Resync fork
plotly/harbor-operator pull request #6
Opened 2024-05-02 20:18 UTC by agateaux

2024-05-07 17:45 UTC, devinturner requested changes

2024-05-07 17:45 UTC, devinturner commented on .github/auto-assignees.yaml
Let's remove this file. We can readd codeowners at a later date.

2024-05-07 17:45 UTC, devinturner commented on .github/workflows/auto-assign-prs.yaml
We can remove this file too.

2024-05-07 17:45 UTC, devinturner commented on MAINTAINERS
Can be removed from our fork

2024-05-07 17:45 UTC, devinturner commented on apis/goharbor.io/v1beta1/harborproject_types.go
@obanby look what we have here ❗ 

I don't think this is something to handle immediately, but now the buildstack can maintain "HarborProject" objects without having to know anything about the inner workings.

2024-05-07 17:45 UTC, devinturner commented on go.mod
This will downgrade a few dependencies. We should revert any of their downgrades.

2024-05-07 17:46 UTC, devinturner commented on apis/goharbor.io/v1beta1/harborproject_types.go
No change requested here, but just wanted to draw attention to it.

2024-05-07 17:50 UTC, agateaux commented on go.mod
I remember I got an issue with the upgrade. Some struct were not available any more in grpc, so the project didn't compile without a code refactoring....

2024-05-07 18:22 UTC, agateaux commented on .github/auto-assignees.yaml
Done

2024-05-07 18:22 UTC, agateaux commented on .github/workflows/auto-assign-prs.yaml
Done

2024-05-07 18:22 UTC, agateaux commented on MAINTAINERS
Done

2024-05-07 18:22 UTC, agateaux commented on go.mod
Done it worked.

2024-05-08 15:04 UTC, devinturner approved these changes
🚀 hell yes. Thank you for getting this ready.

2024-05-08 15:07 UTC, merged

2024-05-08 15:10 UTC, BRONSOLO commented
@devinturner @agateaux is this needed for the 5.4-release?

2024-05-08 17:22 UTC, BRONSOLO commented
Confirmed in 5.4 sync -- this is not needed for 5.4.